apiVersion: v1
entries:
  kubevious:
  - apiVersion: v2
    appVersion: 0.4.10
    created: "2020-03-26T06:15:58.291358858Z"
    description: A Helm chart for Kubevious
    digest: 29d0391ebb04a5eacbf34aeace36e97dd405b0b223986849e27dbff7ee4254cc
    name: kubevious
    type: application
    urls:
    - kubevious-0.4.10.tgz
    version: 0.4.10
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2020-03-26T06:15:58.290852719Z"
    description: A Helm chart for Kubevious server
    digest: 46974e1932a8ea946d416086874d6332e2d66943f3a55bdf2eefc5c9694479b5
    name: kubevious
    type: application
    urls:
    - kubevious-0.1.0.tgz
    version: 0.1.0
generated: "2020-03-26T06:15:58.288129707Z"
