apiVersion: v1
entries:
  kubevious:
  - apiVersion: v2
    appVersion: 0.6.18
    created: "2020-06-24T18:59:23.717680596Z"
    description: A Helm chart for Kubevious
    digest: e3359360b98d7f654bfc5f4fa6d76cff5c032f16d45af15402503239710faaee
    name: kubevious
    type: application
    urls:
    - kubevious-0.6.18.tgz
    version: 0.6.18
  - apiVersion: v2
    appVersion: 0.6.17
    created: "2020-06-24T18:59:23.717063125Z"
    description: A Helm chart for Kubevious
    digest: 1c859c8d539354e6df254bc67e96d69e07ef26867cf72544c38e39c52fde98cf
    name: kubevious
    type: application
    urls:
    - kubevious-0.6.17.tgz
    version: 0.6.17
  - apiVersion: v2
    appVersion: 0.6.16
    created: "2020-06-24T18:59:23.716134497Z"
    description: A Helm chart for Kubevious
    digest: c37b5cdb1cd942b67d4999d233436ec0492c0717989c844c51aa03f1c6748c14
    name: kubevious
    type: application
    urls:
    - kubevious-0.6.16.tgz
    version: 0.6.16
  - apiVersion: v2
    appVersion: 0.6.15
    created: "2020-06-24T18:59:23.715080241Z"
    description: A Helm chart for Kubevious
    digest: 33556960c134b082ffaace3aae9d2b5f361c46619c42913e8b9f28c73cef4c94
    name: kubevious
    type: application
    urls:
    - kubevious-0.6.15.tgz
    version: 0.6.15
  - apiVersion: v2
    appVersion: 0.6.14
    created: "2020-06-24T18:59:23.714166897Z"
    description: A Helm chart for Kubevious
    digest: a609d5ca87f9143edb8e3b67b9fa3726ef47bf72f5d61d5d62389595180b3dba
    name: kubevious
    type: application
    urls:
    - kubevious-0.6.14.tgz
    version: 0.6.14
  - apiVersion: v2
    appVersion: 0.6.13
    created: "2020-06-24T18:59:23.713189414Z"
    description: A Helm chart for Kubevious
    digest: 1fc205ecdf4ac77fb3b7cbab74d7d33158ed45cb4dd711d7324a94f9df7c9875
    name: kubevious
    type: application
    urls:
    - kubevious-0.6.13.tgz
    version: 0.6.13
  - apiVersion: v2
    appVersion: 0.6.12
    created: "2020-06-24T18:59:23.712270973Z"
    description: A Helm chart for Kubevious
    digest: 4155e04646c38e77c269f24ab11652798c7aa49f98686d91218461c8390284ba
    name: kubevious
    type: application
    urls:
    - kubevious-0.6.12.tgz
    version: 0.6.12
  - apiVersion: v2
    appVersion: 0.6.11
    created: "2020-06-24T18:59:23.710882049Z"
    description: A Helm chart for Kubevious
    digest: f0ac2d38352678f7eef9c4afa2dc30e7deee770a554d663afd0706231d8dfc58
    name: kubevious
    type: application
    urls:
    - kubevious-0.6.11.tgz
    version: 0.6.11
  - apiVersion: v2
    appVersion: 0.6.10
    created: "2020-06-24T18:59:23.70907545Z"
    description: A Helm chart for Kubevious
    digest: c0c2af2dd1629df3cc491d3be050b391768ea5987cd96a94c057a41ac57c12c9
    name: kubevious
    type: application
    urls:
    - kubevious-0.6.10.tgz
    version: 0.6.10
  - apiVersion: v2
    appVersion: 0.6.9
    created: "2020-06-24T18:59:23.741013121Z"
    description: A Helm chart for Kubevious
    digest: 9b23435655ff31eb09debbcb2cc519643b5a53ea034de6c256bfbc75bc2df0f8
    name: kubevious
    type: application
    urls:
    - kubevious-0.6.9.tgz
    version: 0.6.9
  - apiVersion: v2
    appVersion: 0.6.8
    created: "2020-06-24T18:59:23.739706371Z"
    description: A Helm chart for Kubevious
    digest: 45e3b57e92688686fae8db7dec3cc2eb14c92fbd4f1a1cbf555d44bb1338d793
    name: kubevious
    type: application
    urls:
    - kubevious-0.6.8.tgz
    version: 0.6.8
  - apiVersion: v2
    appVersion: 0.6.7
    created: "2020-06-24T18:59:23.738442089Z"
    description: A Helm chart for Kubevious
    digest: eae06335d810d9226860712914f357bddfb358cf0ea18210dc25f7723b8748af
    name: kubevious
    type: application
    urls:
    - kubevious-0.6.7.tgz
    version: 0.6.7
  - apiVersion: v2
    appVersion: 0.6.6
    created: "2020-06-24T18:59:23.737052382Z"
    description: A Helm chart for Kubevious
    digest: c8b27ae7700b6a0e80d3e09e3f9d11a54da7962c8c66ad5ff091f412e4740885
    name: kubevious
    type: application
    urls:
    - kubevious-0.6.6.tgz
    version: 0.6.6
  - apiVersion: v2
    appVersion: 0.6.5
    created: "2020-06-24T18:59:23.73439623Z"
    description: A Helm chart for Kubevious
    digest: b82bf2a8bdd3fd2dcdae9ca7130ada10468c63a42cdd7bca8248b365f927c1ce
    name: kubevious
    type: application
    urls:
    - kubevious-0.6.5.tgz
    version: 0.6.5
  - apiVersion: v2
    appVersion: 0.6.4
    created: "2020-06-24T18:59:23.732859383Z"
    description: A Helm chart for Kubevious
    digest: a920c97cc0fc135b3a4a2077a73566fd4bd15f032219fbd49516fd5d7d5af2c0
    name: kubevious
    type: application
    urls:
    - kubevious-0.6.4.tgz
    version: 0.6.4
  - apiVersion: v2
    appVersion: 0.6.3
    created: "2020-06-24T18:59:23.71962401Z"
    description: A Helm chart for Kubevious
    digest: ecb7ca57b0551f12c8140305494a37524b3d1574ba1622957785e529dd581dd1
    name: kubevious
    type: application
    urls:
    - kubevious-0.6.3.tgz
    version: 0.6.3
  - apiVersion: v2
    appVersion: 0.6.2
    created: "2020-06-24T18:59:23.718771004Z"
    description: A Helm chart for Kubevious
    digest: 47263075260c5c94eb27ebe3679f8538646c6924de537235fb15f2365bc7a177
    name: kubevious
    type: application
    urls:
    - kubevious-0.6.2.tgz
    version: 0.6.2
  - apiVersion: v2
    appVersion: 0.6.1
    created: "2020-06-24T18:59:23.708056126Z"
    description: A Helm chart for Kubevious
    digest: 5c5c1500485991be76411538497dc45cf2bb58d9ccd38cd4a69be3fc1e3f6790
    name: kubevious
    type: application
    urls:
    - kubevious-0.6.1.tgz
    version: 0.6.1
  - apiVersion: v2
    appVersion: 0.5.9
    created: "2020-06-24T18:59:23.706952985Z"
    description: A Helm chart for Kubevious
    digest: 8b930c70c5c9e25fa4ed792d4466dbd90a0e685ebeeccbf3a8cf0707b3ff88d2
    name: kubevious
    type: application
    urls:
    - kubevious-0.5.9.tgz
    version: 0.5.9
  - apiVersion: v2
    appVersion: 0.5.8
    created: "2020-06-24T18:59:23.705858007Z"
    description: A Helm chart for Kubevious
    digest: 4fa3f7fe669b0c98f534008f1196c8f509ef6d893c342c60d7571f03aca2da2d
    name: kubevious
    type: application
    urls:
    - kubevious-0.5.8.tgz
    version: 0.5.8
  - apiVersion: v2
    appVersion: 0.5.7
    created: "2020-06-24T18:59:23.704964979Z"
    description: A Helm chart for Kubevious
    digest: 93e81772136b7644661cdfbba08aef144ca19590652b439260ab4fa7b5f21ab2
    name: kubevious
    type: application
    urls:
    - kubevious-0.5.7.tgz
    version: 0.5.7
  - apiVersion: v2
    appVersion: 0.5.6
    created: "2020-06-24T18:59:23.703985621Z"
    description: A Helm chart for Kubevious
    digest: a4ddc42330f97d324caa761a480928e6d7b5d68b4a0d1df27cb669ad8f49c5bc
    name: kubevious
    type: application
    urls:
    - kubevious-0.5.6.tgz
    version: 0.5.6
  - apiVersion: v2
    appVersion: 0.5.4
    created: "2020-06-24T18:59:23.702808504Z"
    description: A Helm chart for Kubevious
    digest: 7820208d43e9524717de5d4e45c027698cc0c8b1ed7455b1c1800947ed541936
    name: kubevious
    type: application
    urls:
    - kubevious-0.5.4.tgz
    version: 0.5.4
  - apiVersion: v2
    appVersion: 0.5.3
    created: "2020-06-24T18:59:23.701907909Z"
    description: A Helm chart for Kubevious
    digest: 116c73de3819e3dd78f5ae19db6daef4786d600cb2c5c3a236e93963345be47b
    name: kubevious
    type: application
    urls:
    - kubevious-0.5.3.tgz
    version: 0.5.3
  - apiVersion: v2
    appVersion: 0.5.2
    created: "2020-06-24T18:59:23.701009873Z"
    description: A Helm chart for Kubevious
    digest: e31dd8f84c31ff56f9f9520897127fa100b5efb5dbf9bf76ab9a77f1f64e18cb
    name: kubevious
    type: application
    urls:
    - kubevious-0.5.2.tgz
    version: 0.5.2
  - apiVersion: v2
    appVersion: 0.5.1
    created: "2020-06-24T18:59:23.700131496Z"
    description: A Helm chart for Kubevious
    digest: cb9b7702af67f7b0b6475de7c51296228f0d507cfd1272c7cad8ca19d401e3a5
    name: kubevious
    type: application
    urls:
    - kubevious-0.5.1.tgz
    version: 0.5.1
  - apiVersion: v2
    appVersion: 0.4.24
    created: "2020-06-24T18:59:23.699353069Z"
    description: A Helm chart for Kubevious
    digest: 9806228bbf990d68cf6ce63486ae75748bc9af61c9b6133c8e775e0592880bf8
    name: kubevious
    type: application
    urls:
    - kubevious-0.4.24.tgz
    version: 0.4.24
  - apiVersion: v2
    appVersion: 0.4.23
    created: "2020-06-24T18:59:23.698558114Z"
    description: A Helm chart for Kubevious
    digest: c390acdd73b5e1bcc73f363371140fdeb9513f189bb8b62b2243ed12490f7f74
    name: kubevious
    type: application
    urls:
    - kubevious-0.4.23.tgz
    version: 0.4.23
  - apiVersion: v2
    appVersion: 0.4.22
    created: "2020-06-24T18:59:23.697792463Z"
    description: A Helm chart for Kubevious
    digest: fc4f87dcf03832a86b00fe30c2e335d803d8b03eca6c10eae995a12f116387bf
    name: kubevious
    type: application
    urls:
    - kubevious-0.4.22.tgz
    version: 0.4.22
  - apiVersion: v2
    appVersion: 0.4.21
    created: "2020-06-24T18:59:23.69699001Z"
    description: A Helm chart for Kubevious
    digest: 12d22f41c12054318f4d8f36512023fe0298fab2caa6331cff583251a540579d
    name: kubevious
    type: application
    urls:
    - kubevious-0.4.21.tgz
    version: 0.4.21
  - apiVersion: v2
    appVersion: 0.4.20
    created: "2020-06-24T18:59:23.686891969Z"
    description: A Helm chart for Kubevious
    digest: 848b7b6353e880e95072248f0acab526beaf757f3688caee52d903c287bc03e9
    name: kubevious
    type: application
    urls:
    - kubevious-0.4.20.tgz
    version: 0.4.20
  - apiVersion: v2
    appVersion: 0.4.19
    created: "2020-06-24T18:59:23.685714652Z"
    description: A Helm chart for Kubevious
    digest: 013b2aa74ba3c0c4a5cdbce6eb5ea087a4227387270a61b8641925106016a2d6
    name: kubevious
    type: application
    urls:
    - kubevious-0.4.19.tgz
    version: 0.4.19
  - apiVersion: v2
    appVersion: 0.4.18
    created: "2020-06-24T18:59:23.684513469Z"
    description: A Helm chart for Kubevious
    digest: f244ffd87d75b9f36bf0faaeeafd57569b2fbd0d3990083648054228bbcc4612
    name: kubevious
    type: application
    urls:
    - kubevious-0.4.18.tgz
    version: 0.4.18
  - apiVersion: v2
    appVersion: 0.4.17
    created: "2020-06-24T18:59:23.683136467Z"
    description: A Helm chart for Kubevious
    digest: c84726c66c1f75bfd6d0d6eb3c4d9219e803abb9ab324e18fd65f754e55f75db
    name: kubevious
    type: application
    urls:
    - kubevious-0.4.17.tgz
    version: 0.4.17
  - apiVersion: v2
    appVersion: 0.4.16
    created: "2020-06-24T18:59:23.68195939Z"
    description: A Helm chart for Kubevious
    digest: b534aa3aae95bdf51b8a616d6f7bcc83cfc873cd331d06e53578ae7327eb0416
    name: kubevious
    type: application
    urls:
    - kubevious-0.4.16.tgz
    version: 0.4.16
  - apiVersion: v2
    appVersion: 0.4.15
    created: "2020-06-24T18:59:23.680676598Z"
    description: A Helm chart for Kubevious
    digest: 1bab0a5f2650b62cc7b03b158098c6ef835c2305f7a9c4ffedfe613cc4c1a7f2
    name: kubevious
    type: application
    urls:
    - kubevious-0.4.15.tgz
    version: 0.4.15
  - apiVersion: v2
    appVersion: 0.4.14
    created: "2020-06-24T18:59:23.679836269Z"
    description: A Helm chart for Kubevious
    digest: 12aaedf65e0e03ee91e4a93a4619e309f742d56cd39b4e8c100a5538c7f54632
    name: kubevious
    type: application
    urls:
    - kubevious-0.4.14.tgz
    version: 0.4.14
  - apiVersion: v2
    appVersion: 0.4.13
    created: "2020-06-24T18:59:23.679072467Z"
    description: A Helm chart for Kubevious
    digest: 2844264a4a85805235a39fee0f644d9ee0c506aa99d33e76354b0868d196dac4
    name: kubevious
    type: application
    urls:
    - kubevious-0.4.13.tgz
    version: 0.4.13
  - apiVersion: v2
    appVersion: 0.4.12
    created: "2020-06-24T18:59:23.67831541Z"
    description: A Helm chart for Kubevious
    digest: e6f9e408a42fbb55f70b1272648882b7e563b179c20f222469fc750ab5e27606
    name: kubevious
    type: application
    urls:
    - kubevious-0.4.12.tgz
    version: 0.4.12
  - apiVersion: v2
    appVersion: 0.4.11
    created: "2020-06-24T18:59:23.677616525Z"
    description: A Helm chart for Kubevious
    digest: 26c6a0d6201291261bfef8fe5e17396da8954c90653e1ef407533d7b6ac04a20
    name: kubevious
    type: application
    urls:
    - kubevious-0.4.11.tgz
    version: 0.4.11
  - apiVersion: v2
    appVersion: 0.4.10
    created: "2020-06-24T18:59:23.676934663Z"
    description: A Helm chart for Kubevious
    digest: cb3942be3764e43252f4dc637393855aaa728e6942131262e7d71c64cd464d63
    name: kubevious
    type: application
    urls:
    - kubevious-0.4.10.tgz
    version: 0.4.10
  - apiVersion: v2
    appVersion: "0.3"
    created: "2020-06-24T18:59:23.676204896Z"
    description: A Helm chart for Kubevious
    digest: bd6f0c3e32280b6ee0e22becc824af67e23e741e45925627fb61b4a7028943b0
    name: kubevious
    type: application
    urls:
    - kubevious-0.3.tgz
    version: "0.3"
  - apiVersion: v2
    appVersion: "0.2"
    created: "2020-06-24T18:59:23.67540434Z"
    description: A Helm chart for Kubevious
    digest: cc7b92fc4987016d5e00a97d662182c8534575405d835ebab34063dcde33d769
    name: kubevious
    type: application
    urls:
    - kubevious-0.2.tgz
    version: "0.2"
  - apiVersion: v2
    appVersion: "0.1"
    created: "2020-06-24T18:59:23.674592752Z"
    description: A Helm chart for Kubevious
    digest: e86855b7058db905bddf6ddbacf9e07f6f1b5359d34724359f87f6025ae62c69
    name: kubevious
    type: application
    urls:
    - kubevious-0.1.tgz
    version: "0.1"
generated: "2020-06-24T18:59:23.673441288Z"
