{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kubevious
  namespace: {{ .Release.Namespace }}
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.allow-http: "true"
{{- if .Values.ingress.class }}
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
{{- end }}
{{- if .Values.ingress.staticIpName }}
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.ingress.staticIpName }}
{{- end }}
{{- if .Values.ingress.annotations }}
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
{{- if eq .Values.provider "gke" }}
{{- if .Values.ingress.domain }}
    networking.gke.io/managed-certificates: kubevious-certificate
{{- end }}
{{- end }}
spec:
  rules:
  - http:
      paths:
        # - path: /api/*
        #   backend:
        #     serviceName: {{ .Values.kubevious.svcName }}
        #     servicePort: {{ .Values.kubevious.port }}
        - path: /*
          backend:
            serviceName: {{ .Values.ui.svcName }}
            servicePort: {{ .Values.ui.port }}
    {{- if .Values.ingress.domain }}
    host: {{ .Values.ingress.domain }}
    {{- end}}
{{- end }}