provider: none
ingress:
  enabled: false
  class: null
  domain: null
  staticIpName: null
  annotations: {}
kubevious:
  image:
    repository: kubevious/kubevious
    tag: 0.4.8
    pullPolicy: IfNotPresent
  name: kubevious
  svcName: kubevious-svc
  port: 4000
  cpu: 100m
  memory: 200Mi
parser:
  image:
    repository: kubevious/parser
    tag: unknown
    pullPolicy: IfNotPresent
  name: kubevious-parser
  port: 4500
  cpu: 100m
  memory: 200Mi
ui:
  image:
    repository: kubevious/ui
    tag: 0.4.4
    pullPolicy: IfNotPresent
  name: kubevious-ui
  svcName: kubevious-ui-svc
  port: 3000
  cpu: 25m
  memory: 100Mi
mysql:
  image:
    repository: mysql
    tag: 8.0.19
    pullPolicy: IfNotPresent
  name: kubevious-mysql
  svcName: kubevious-mysql-svc
  port: 3306
  cpu: 50m
  memory: 500Mi
  storage: 10Gi
