provider: none
ingress:
  enabled: false
  class: null
  domain: null
  staticIpName: null
  annotations: {}
  labels: {}
  tls: false
  tlsSecretName: null
kubevious:
  image:
    repository: kubevious/kubevious
    tag: 0.6.40
    pullPolicy: IfNotPresent
  name: kubevious
  svcName: kubevious-svc
  port: 4001
  cpu: 100m
  memory: 200Mi
parser:
  image:
    repository: kubevious/parser
    tag: 0.6.16
    pullPolicy: IfNotPresent
  name: kubevious-parser
  port: 4002
  cpu: 100m
  memory: 200Mi
ui:
  image:
    repository: kubevious/ui
    tag: 0.6.29
    pullPolicy: IfNotPresent
  name: kubevious-ui
  svcName: kubevious-ui-svc
  port: 80
  cpu: 25m
  memory: 100Mi
mysql:
  image:
    repository: mysql
    tag: 8.0.19
    pullPolicy: IfNotPresent
  name: kubevious-mysql
  svcName: kubevious-mysql-svc
  port: 3306
  cpu: 50m
  memory: 500Mi
  storage: 10Gi
  storageClass: null
  db: kubevious
  user: root
  pass: ""
