apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubevious
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubevious
subjects:
- kind: ServiceAccount
  name: kubevious
  namespace: {{ .Release.Namespace }}